version: "3.8"

services:
  pitchcraft-api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      PGSSLROOTCERT: /certs/aws-rds-cert.pem
    volumes:
      - ./certs:/certs:ro
    ports:
      - "8000:8000"